package com.bdsht.xinehealth.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseXhUserHealthInfo<M extends BaseXhUserHealthInfo<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setOpenid(java.lang.String openid) {
		set("openid", openid);
	}

	public java.lang.String getOpenid() {
		return get("openid");
	}

	public void setUnionid(java.lang.String unionid) {
		set("unionid", unionid);
	}

	public java.lang.String getUnionid() {
		return get("unionid");
	}

	public void setDate(java.lang.String date) {
		set("date", date);
	}

	public java.lang.String getDate() {
		return get("date");
	}

	public void setTime(java.lang.String time) {
		set("time", time);
	}

	public java.lang.String getTime() {
		return get("time");
	}

	public void setBloodSI(java.lang.String bloodSI) {
		set("bloodSI", bloodSI);
	}

	public java.lang.String getBloodSI() {
		return get("bloodSI");
	}

	public void setBloodPI(java.lang.String bloodPI) {
		set("bloodPI", bloodPI);
	}

	public java.lang.String getBloodPI() {
		return get("bloodPI");
	}

	public void setBloodLI(java.lang.String bloodLI) {
		set("bloodLI", bloodLI);
	}

	public java.lang.String getBloodLI() {
		return get("bloodLI");
	}

}
