package com.bdsht.xinehealth.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseNews<M extends BaseNews<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setTitle(java.lang.String title) {
		set("title", title);
	}

	public java.lang.String getTitle() {
		return get("title");
	}

	public void setPicurl(java.lang.String picurl) {
		set("picurl", picurl);
	}

	public java.lang.String getPicurl() {
		return get("picurl");
	}

	public void setUrl(java.lang.String url) {
		set("url", url);
	}

	public java.lang.String getUrl() {
		return get("url");
	}

	public void setShoworder(java.lang.Integer showorder) {
		set("showorder", showorder);
	}

	public java.lang.Integer getShoworder() {
		return get("showorder");
	}

	public void setEnabled(java.lang.Integer enabled) {
		set("enabled", enabled);
	}

	public java.lang.Integer getEnabled() {
		return get("enabled");
	}

}
