package com.bdsht.xinehealth.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseXhAdminOptlog<M extends BaseXhAdminOptlog<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setBeanName(java.lang.String beanName) {
		set("bean_name", beanName);
	}

	public java.lang.String getBeanName() {
		return get("bean_name");
	}

	public void setCreateTime(java.lang.String createTime) {
		set("create_time", createTime);
	}

	public java.lang.String getCreateTime() {
		return get("create_time");
	}

	public void setMethodName(java.lang.String methodName) {
		set("method_name", methodName);
	}

	public java.lang.String getMethodName() {
		return get("method_name");
	}

	public void setOptName(java.lang.String optName) {
		set("opt_name", optName);
	}

	public java.lang.String getOptName() {
		return get("opt_name");
	}

	public void setOptObjId(java.lang.String optObjId) {
		set("opt_obj_id", optObjId);
	}

	public java.lang.String getOptObjId() {
		return get("opt_obj_id");
	}

	public void setOptStyle(java.lang.String optStyle) {
		set("opt_style", optStyle);
	}

	public java.lang.String getOptStyle() {
		return get("opt_style");
	}

	public void setRemoteAddr(java.lang.String remoteAddr) {
		set("remote_addr", remoteAddr);
	}

	public java.lang.String getRemoteAddr() {
		return get("remote_addr");
	}

	public void setUserName(java.lang.String userName) {
		set("user_name", userName);
	}

	public java.lang.String getUserName() {
		return get("user_name");
	}

	public void setActionName(java.lang.String actionName) {
		set("action_name", actionName);
	}

	public java.lang.String getActionName() {
		return get("action_name");
	}

	public void setRequestTime(java.lang.String requestTime) {
		set("request_time", requestTime);
	}

	public java.lang.String getRequestTime() {
		return get("request_time");
	}

	public void setSessionId(java.lang.String sessionId) {
		set("session_id", sessionId);
	}

	public java.lang.String getSessionId() {
		return get("session_id");
	}

	public void setUri(java.lang.String uri) {
		set("uri", uri);
	}

	public java.lang.String getUri() {
		return get("uri");
	}

}
