package com.bdsht.xinehealth.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("food_info", "id", FoodInfo.class);
		arp.addMapping("member", "id", Member.class);
		arp.addMapping("news", "id", News.class);
		arp.addMapping("news_latest", "id", NewsLatest.class);
		arp.addMapping("user", "id", User.class);
		arp.addMapping("user_checksign", "id", UserChecksign.class);
		arp.addMapping("user_cmd", "id", UserCmd.class);
		arp.addMapping("user_sign", "id", UserSign.class);
		arp.addMapping("weixinuserinfo", "id", Weixinuserinfo.class);
		arp.addMapping("xh_admin_optlog", "id", XhAdminOptlog.class);
		arp.addMapping("xh_admin_user", "id", XhAdminUser.class);
		arp.addMapping("xh_classicrecipes", "id", XhClassicrecipes.class);
		arp.addMapping("xh_ingredients", "id", XhIngredients.class);
		arp.addMapping("xh_job_food_news", "id", XhJobFoodNews.class);
		arp.addMapping("xh_job_link", "id", XhJobLink.class);
		arp.addMapping("xh_link", "id", XhLink.class);
		arp.addMapping("xh_nutritional", "id", XhNutritional.class);
		arp.addMapping("xh_recipe", "id", XhRecipe.class);
		arp.addMapping("xh_style", "id", XhStyle.class);
		arp.addMapping("xh_title", "id", XhTitle.class);
		arp.addMapping("xh_user_collection", "id", XhUserCollection.class);
		arp.addMapping("xh_user_comment", "id", XhUserComment.class);
		arp.addMapping("xh_user_health_info", "id", XhUserHealthInfo.class);
		arp.addMapping("xh_user_info", "id", XhUserInfo.class);
		arp.addMapping("xh_user_sharing", "id", XhUserSharing.class);
		arp.addMapping("xinedata_authority", "id", XinedataAuthority.class);
		arp.addMapping("xinedata_message", "id", XinedataMessage.class);
		arp.addMapping("xinedata_symptoms", "id", XinedataSymptoms.class);
	}
}

