package com.bdsht.xinehealth.model;

import java.util.List;

import com.bdsht.xinehealth.model.base.BaseFoodInfo;
import com.jfinal.plugin.activerecord.Page;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FoodInfo extends BaseFoodInfo<FoodInfo> {
	public static final FoodInfo dao = new FoodInfo();

	public List<FoodInfo> findAll(){
		return this.find("select * from food_info order by id DESC");
	}

	public boolean existByName(String name){

		FoodInfo foodInfo=this.findFirst("select * from food_info where name=?",name);
		if(foodInfo!=null) 
			return true;
		else
			return false;

	}
	
	public FoodInfo findById(int id){
		return this.findFirst("select * from food_info where id=?",id);
	}
	
	public Page<FoodInfo> paginate(int pageNumber, int pageSize) {
		return paginate(pageNumber, pageSize, "select *", "from food_info order by id asc");
	}

	public FoodInfo findByName(String name) {
		return this.findFirst("select * from food_info where name=?",name);
	}

	public List<FoodInfo> findBySpecies(String species) {
		return this.find("select * from food_info where species=?",species);
	}
}
