package com.bdsht.xinehealth.model;

import com.bdsht.xinehealth.model.base.BaseNewsLatest;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class NewsLatest extends BaseNewsLatest<NewsLatest> {
	public static final NewsLatest dao = new NewsLatest();
}
