package com.bdsht.xinehealth.model;

import com.bdsht.xinehealth.model.base.BaseNews;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class News extends BaseNews<News> {
	public static final News dao = new News();
}
