package com.bdsht.xinehealth.model;

import com.bdsht.xinehealth.model.base.BaseUserCmd;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserCmd extends BaseUserCmd<UserCmd> {
	public static final UserCmd dao = new UserCmd();
}
