package com.bdsht.xinehealth.model;

import com.bdsht.xinehealth.model.base.BaseUserChecksign;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserChecksign extends BaseUserChecksign<UserChecksign> {
	public static final UserChecksign dao = new UserChecksign();
}
