package com.bdsht.xinehealth.model;

import com.bdsht.xinehealth.model.base.BaseUserSign;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserSign extends BaseUserSign<UserSign> {
	public static final UserSign dao = new UserSign();
}
