package com.bdsht.xinehealth.model;

import java.util.List;

import com.bdsht.xinehealth.model.base.BaseWeixinuserinfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Weixinuserinfo extends BaseWeixinuserinfo<Weixinuserinfo> {
	public static final Weixinuserinfo dao = new Weixinuserinfo();
	public Weixinuserinfo findByOpenid(String openid){
		return this.findFirst("select * from weixinuserinfo where openid=?",openid);
	}
	
	public List<Weixinuserinfo> findAll(){
		return this.find("select * from weixinuserinfo");
	}
}
