package com.bdsht.xinehealth.model;

import java.util.List;

import com.bdsht.xinehealth.model.base.BaseXhAdminOptlog;
import com.jfinal.plugin.activerecord.Page;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class XhAdminOptlog extends BaseXhAdminOptlog<XhAdminOptlog> {
	public static final XhAdminOptlog dao = new XhAdminOptlog();
	
	public List<XhAdminOptlog> findAll(){
		return this.find("select * from xh_admin_optlog order by id DESC");
	}

	public Page<XhAdminOptlog> paginate(int pageNumber, int pageSize) {
		return paginate(pageNumber, pageSize, "select *", "from xh_admin_optlog order by id asc");
	}

	public List<XhAdminOptlog> findByUserName(String userName) {
		return this.find("select * from xh_admin_optlog where user_name=? order by id DESC",userName);
	}

}
