package com.bdsht.xinehealth.model;

import java.util.List;

import com.bdsht.xinehealth.model.base.BaseXhAdminUser;
import com.jfinal.plugin.activerecord.Page;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class XhAdminUser extends BaseXhAdminUser<XhAdminUser> {
	public static final XhAdminUser dao = new XhAdminUser();
	
	public List<XhAdminUser> findAll(){

		return this.find("select * from xh_admin_user");

	}

	public XhAdminUser findByIdAndTimestamp(int id,String timestamp){

		return this.findFirst("select * from xh_admin_user where id=? and timestamp=?",id,timestamp);

	}

	public XhAdminUser findById(int id){
		return this.findFirst("select * from xh_admin_user where id=?",id);

	}
	public XhAdminUser findByName(String name){
		return this.findFirst("select * from xh_admin_user where name=?",name);

	}

	public Page<XhAdminUser> paginate(int pageNumber, int pageSize) {
		return paginate(pageNumber, pageSize, "select *", "from xh_admin_user order by id asc");
	}

	public XhAdminUser findByUserId(String userId) {
		 return this.findFirst("select * from xh_admin_user where userId=?",userId);
	}

	public XhAdminUser findByUserIdAndUserPwd(String userId, String userPwd) {
	   return this.findFirst("select * from xh_admin_user where userId=? and userPwd=?",userId,userPwd);
	}

}
