package com.bdsht.xinehealth.model;

import java.util.List;

import com.bdsht.xinehealth.model.base.BaseXhClassicrecipes;
import com.jfinal.plugin.activerecord.Page;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class XhClassicrecipes extends BaseXhClassicrecipes<XhClassicrecipes> {
	public static final XhClassicrecipes dao = new XhClassicrecipes();
	
	public List<XhClassicrecipes> findAll(){

		return this.find("select * from xh_classicRecipes");

	}

	public XhClassicrecipes findByIdAndTimestamp(int id,String timestamp){

		return this.findFirst("select * from xh_classicRecipes where id=? and timestamp=?",id,timestamp);

	}

	public XhClassicrecipes findById(int id){
		return this.findFirst("select * from xh_classicRecipes where id=?",id);

	}
	public List<XhClassicrecipes> findByIngreId(int ingreId){
		return this.find("select * from xh_classicRecipes where food_style_ingreId=?",ingreId);

	}

	public Page<XhClassicrecipes> paginate(int pageNumber, int pageSize) {
		return paginate(pageNumber, pageSize, "select *", "from xh_classicRecipes order by id asc");
	}

	public XhClassicrecipes findByTitle(String title) {
		return this.findFirst("select * from xh_classicRecipes where title=?",title);
	}
	
}
