package com.bdsht.xinehealth.model;

import java.util.List;

import com.bdsht.xinehealth.model.base.BaseXhIngredients;
import com.jfinal.plugin.activerecord.Page;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class XhIngredients extends BaseXhIngredients<XhIngredients> {
	public static final XhIngredients dao = new XhIngredients();
	
	public List<XhIngredients> findAll(){

		return this.find("select * from xh_ingredients");

	}

	public XhIngredients findByIdAndTimestamp(int id,String timestamp){

		return this.findFirst("select * from xh_ingredients where id=? and timestamp=?",id,timestamp);

	}

	public XhIngredients findById(int id){
		return this.findFirst("select * from xh_ingredients where id=?",id);

	}
	public XhIngredients findByName(String name){
		return this.findFirst("select * from xh_ingredients where name=?",name);

	}

	public Page<XhIngredients> paginate(int pageNumber, int pageSize) {
		return paginate(pageNumber, pageSize, "select *", "from xh_ingredients order by id asc");
	}

	public List<XhIngredients> findByStyleId(int styleId) {
		return this.find("select * from xh_ingredients where food_style_sId=?",styleId);
	}

	
}
