package com.bdsht.xinehealth.model;

import java.util.List;

import com.bdsht.xinehealth.model.base.BaseXhJobLink;
import com.jfinal.plugin.activerecord.Page;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class XhJobLink extends BaseXhJobLink<XhJobLink> {
	public static final XhJobLink dao = new XhJobLink();
	

	public List<XhJobLink> findAll(){

		return this.find("select * from xh_job_link");

	}

	public XhJobLink findByIdAndTimestamp(int id,String timestamp){

		return this.findFirst("select * from xh_job_link where id=? and timestamp=?",id,timestamp);

	}

	public XhJobLink findById(int id){
		return this.findFirst("select * from xh_job_link where id=?",id);

	}
	public XhJobLink findByName(String name){
		return this.findFirst("select * from xh_job_link where name=?",name);

	}

	public Page<XhJobLink> paginate(int pageNumber, int pageSize) {
		return paginate(pageNumber, pageSize, "select *", "from xh_job_link order by id asc");
	}

}
