package com.bdsht.xinehealth.model;

import java.util.List;

import com.bdsht.xinehealth.model.base.BaseXhNutritional;
import com.jfinal.plugin.activerecord.Page;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class XhNutritional extends BaseXhNutritional<XhNutritional> {
	public static final XhNutritional dao = new XhNutritional();
	
	public List<XhNutritional> findAll(){

		return this.find("select * from xh_nutritional");

	}

	public XhNutritional findByIdAndTimestamp(int id,String timestamp){

		return this.findFirst("select * from xh_nutritional where id=? and timestamp=?",id,timestamp);

	}

	public XhNutritional findById(int id){
		return this.findFirst("select * from xh_nutritional where id=?",id);

	}
	public XhNutritional findByIngreId(int ingreId){
		return this.findFirst("select * from xh_nutritional where food_style_ingreId=?",ingreId);

	}

	public Page<XhNutritional> paginate(int pageNumber, int pageSize) {
		return paginate(pageNumber, pageSize, "select *", "from xh_nutritional order by id asc");
	}

}
