package com.bdsht.xinehealth.model;

import java.util.List;

import com.bdsht.xinehealth.model.base.BaseXhRecipe;
import com.jfinal.plugin.activerecord.Page;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class XhRecipe extends BaseXhRecipe<XhRecipe> {
	public static final XhRecipe dao = new XhRecipe();
	
	public List<XhRecipe> findAll(){

		return this.find("select * from xh_recipe");

	}

	public XhRecipe findByIdAndTimestamp(int id,String timestamp){

		return this.findFirst("select * from xh_recipe where id=? and timestamp=?",id,timestamp);

	}

	public XhRecipe findById(int id){
		return this.findFirst("select * from xh_recipe where id=?",id);

	}
	public XhRecipe findByName(String name){
		return this.findFirst("select * from xh_recipe where name=?",name);

	}

	public Page<XhRecipe> paginate(int pageNumber, int pageSize) {
		return paginate(pageNumber, pageSize, "select *", "from xh_recipe order by id asc");
	}

	public List<XhRecipe> findByStyleId(int styleId) {
		return this.find("select * from xh_recipe where food_style_sId=?",styleId);
	}


}
