package com.bdsht.xinehealth.model;

import java.util.List;

import com.bdsht.xinehealth.model.base.BaseXhTitle;
import com.jfinal.plugin.activerecord.Page;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class XhTitle extends BaseXhTitle<XhTitle> {
	public static final XhTitle dao = new XhTitle();

	public List<XhTitle> findAll(){

		return this.find("select * from xh_title");

	}

	public XhTitle findByIdAndTimestamp(int id,String timestamp){

		return this.findFirst("select * from xh_title where id=? and timestamp=?",id,timestamp);

	}

	public XhTitle findById(int id){
		return this.findFirst("select * from xh_title where id=?",id);

	}
	public XhTitle findByName(String name){
		return this.findFirst("select * from xh_title where name=?",name);

	}

	public Page<XhTitle> paginate(int pageNumber, int pageSize) {
		return paginate(pageNumber, pageSize, "select *", "from xh_title order by id asc");
	}
}
