package com.bdsht.xinehealth.model;

import com.bdsht.xinehealth.model.base.BaseXhUserComment;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class XhUserComment extends BaseXhUserComment<XhUserComment> {
	public static final XhUserComment dao = new XhUserComment();
}
