package com.bdsht.xinehealth.model;

import com.bdsht.xinehealth.model.base.BaseXhUserHealthInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class XhUserHealthInfo extends BaseXhUserHealthInfo<XhUserHealthInfo> {
	public static final XhUserHealthInfo dao = new XhUserHealthInfo();
}
