package com.bdsht.xinehealth.model;

import com.bdsht.xinehealth.model.base.BaseXhUserCollection;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class XhUserCollection extends BaseXhUserCollection<XhUserCollection> {
	public static final XhUserCollection dao = new XhUserCollection();
}
