package com.bdsht.xinehealth.model;

import com.bdsht.xinehealth.model.base.BaseXhUserSharing;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class XhUserSharing extends BaseXhUserSharing<XhUserSharing> {
	public static final XhUserSharing dao = new XhUserSharing();
}
