package com.bdsht.xinehealth.model;

import com.bdsht.xinehealth.model.base.BaseXhUserInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class XhUserInfo extends BaseXhUserInfo<XhUserInfo> {
	public static final XhUserInfo dao = new XhUserInfo();
}
