package com.bdsht.xinehealth.model;

import com.bdsht.xinehealth.model.base.BaseXinedataMessage;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class XinedataMessage extends BaseXinedataMessage<XinedataMessage> {
	public static final XinedataMessage dao = new XinedataMessage();
}
