package com.bdsht.xinehealth.model;

import com.bdsht.xinehealth.model.base.BaseXinedataAuthority;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class XinedataAuthority extends BaseXinedataAuthority<XinedataAuthority> {
	public static final XinedataAuthority dao = new XinedataAuthority();
}
