package com.bdsht.xinehealth.model;

import java.util.List;

import com.bdsht.xinehealth.model.base.BaseXinedataSymptoms;
import com.jfinal.plugin.activerecord.Page;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class XinedataSymptoms extends BaseXinedataSymptoms<XinedataSymptoms> {
	public static final XinedataSymptoms dao = new XinedataSymptoms();
	
	public List<XinedataSymptoms> findAll(){
		return this.find("select * from xinedata_symptoms order by id DESC");
	}
	public List<XinedataSymptoms> findByName(String name){
		return this.find("select * from xinedata_symptoms where name=?",name);
	}
	
	public Page<XinedataSymptoms> paginate(int pageNumber, int pageSize) {
		return paginate(pageNumber, pageSize, "select *", "from xinedata_symptoms order by id asc");
	}
}
